---

- hosts: all
  become: true
  tasks:

  - name: update respository
    apt:
     update_cache: yes

  - name: Install apache2 package
    apt:
      name: apache2
    when: ansible_distribution == "CentOS"

  - name: add php support for apache
    apt:
      name: libapache2-mod-php
    when: ansible_distribution == "CentOS"
