---
- name: install and manage services
  hosts: all
  become: true

  tasks:

    - name: Install apache httpd
      apt:
        name: apache2
        state: latest
      when: ansible_distribution == 'Ubuntu'

